pipeline:
  publish:
     image: plugins/docker
     pull: never
     registry: registry.cn-hangzhou.aliyuncs.com
     repo: registry.cn-hangzhou.aliyuncs.com/ybase/test
     secrets: [docker_username,docker_password]
     tags: latest
