kind: pipeline
name: default
clone:
  depth: 50
steps:
  - name: publish
    image: plugins/docker
    restore: true
    settings:
     repo: registry.cn-hangzhou.aliyuncs.com/ybase/test
     registry: registry.cn-hangzhou.aliyuncs.com
     username:
       from_secret: docker_username
     password:
       from_secret: docker_password
     auto_tag: true
     launch_debug: true
     trigger:
       event:
       - push
       - tag
       - pull_request
  - name: deploy
    image: golang
    commands:
    - echo ${DRONE_TAG}
    when:
      status:
      - success
