kind: pipeline
name: default
steps:
  -  name: publish
     image: plugins/docker
     restore: true
     settings:
     	repo: registry.cn-hangzhou.aliyuncs.com/ybase/test
     	username:
           from_secret: docker_username
        password:
           from_secret: docker_password
     	tags: ${DRONE_TAG=latest}
     	when:
          event: [push, tag, deployment]
