kind: pipeline
name: test
steps:
- name: push
  image: plugins/docker
  settings:
    repo: registry.cn-hangzhou.aliyuncs.com/ybase/test
    tags: latest
    username:
      from_secret: username
    password:
      from_secret: pwd
