kind: pipeline
name: default
clone:
  depth: 50
steps:
  - name: publish
    image: plugins/docker
    restore: true
    settings:
     repo: registry.cn-hangzhou.aliyuncs.com/ybase/test
     registry: registry.cn-hangzhou.aliyuncs.com
     username:
       from_secret: docker_username
     password:
       from_secret: docker_password
     auto_tag: true
     launch_debug: true
     trigger:
       event:
       - push
       - tag
       - pull_request
  - name: deploy
    image: vallard/drone-kube
    settings:
      template: dep.yml
      server: https://192.168.1.63:6443
      ca:
        from_secret: k8s_ca
      token:
        from_secret: k8s_token
    when:
     ref:
      include:
      - refs/tags/*.rc.1
      status:
      - success
