apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: test1
  namespace: signer
spec:
  selector:
    matchLabels:
      app: test1
  replicas: 1
  template:
    metadata:
      labels:
        app: test1
    spec:
      containers:
         - name: test
           image: registry.cn-hangzhou.aliyuncs.com/ybase/{{repo.name}}:{{build.tag}}
           ports:
           - containerPort: 8080
      imagePullPolicy: Always
      imagePullSecrets:
          - name: aliyunsecret
      restartPolicy: Always
