apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: tencent-entities
spec:
  selector:
    matchLabels:
      app:  tencent-entities
  replicas: 3 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: tencent-entities
    spec:
      containers:
         - name: tencent-entities
           image: registry.cn-hangzhou.aliyuncs.com/ybase/tencent_entities:latest
           ports:
           - containerPort: 8080
           volumeMounts:
           - mountPath: /db
             name: tencent-entities-volume
      imagePullPolicy: Always
      imagePullSecrets:
          - name: aliyunsecret
      restartPolicy: Always
      volumes:
      - name: tencent-entities-volume
        persistentVolumeClaim:
                 claimName: pvc-103
---
apiVersion: v1
kind: Service
metadata:
  name: encent-entities-api
  labels:
    app: encent-entities-api
spec:
  type: NodePort
  ports:
  - port: 8080
    name: http
    nodePort: 30080
  selector:
        app: tencent-entities