apiVersion: apps/v1
kind: Deployment
metadata:
  name: test
  namespace: kawkeye
spec:
  selector:
    matchLabels:
      app: test
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: test
    spec:
      containers:
         - name: test
           image: {{repo.name}}
           ports:
           - containerPort: 8080
      imagePullPolicy: Always
      imagePullSecrets:
          - name: aliyunsecret
      restartPolicy: Always
